# Generated by Django 3.0.5 on 2020-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='duvidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('duvidas', models.CharField(max_length=100, verbose_name='duvidas')),
            ],
        ),
        migrations.CreateModel(
            name='Parceirias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('proposta', models.CharField(max_length=100, verbose_name='proposta')),
            ],
        ),
    ]
